#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSConsolidator.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="posconsolidator")]
	public partial class POSConsolidatorDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTrnSale(TrnSale instance);
    partial void UpdateTrnSale(TrnSale instance);
    partial void DeleteTrnSale(TrnSale instance);
    #endregion
		
		public POSConsolidatorDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["posconsolidatorConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public POSConsolidatorDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POSConsolidatorDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POSConsolidatorDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POSConsolidatorDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TrnSale> TrnSales
		{
			get
			{
				return this.GetTable<TrnSale>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnSales")]
	public partial class TrnSale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _SalesDate;
		
		private string _SalesNumber;
		
		private string _ORNumber;
		
		private decimal _Amount;
		
		private decimal _VATSales;
		
		private decimal _NonVATSales;
		
		private decimal _VATAmount;
		
		private string _Customer;
		
		private string _Discount;
		
		private string _SeniorCitizenId;
		
		private string _SeniorCitizenName;
		
		private System.Nullable<int> _SeniorCitizenAge;
		
		private string _Remarks;
		
		private string _Terminal;
		
		private bool _IsCancelled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSalesDateChanging(System.DateTime value);
    partial void OnSalesDateChanged();
    partial void OnSalesNumberChanging(string value);
    partial void OnSalesNumberChanged();
    partial void OnORNumberChanging(string value);
    partial void OnORNumberChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnVATSalesChanging(decimal value);
    partial void OnVATSalesChanged();
    partial void OnNonVATSalesChanging(decimal value);
    partial void OnNonVATSalesChanged();
    partial void OnVATAmountChanging(decimal value);
    partial void OnVATAmountChanged();
    partial void OnCustomerChanging(string value);
    partial void OnCustomerChanged();
    partial void OnDiscountChanging(string value);
    partial void OnDiscountChanged();
    partial void OnSeniorCitizenIdChanging(string value);
    partial void OnSeniorCitizenIdChanged();
    partial void OnSeniorCitizenNameChanging(string value);
    partial void OnSeniorCitizenNameChanged();
    partial void OnSeniorCitizenAgeChanging(System.Nullable<int> value);
    partial void OnSeniorCitizenAgeChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnTerminalChanging(string value);
    partial void OnTerminalChanged();
    partial void OnIsCancelledChanging(bool value);
    partial void OnIsCancelledChanged();
    #endregion
		
		public TrnSale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesDate", DbType="DateTime NOT NULL")]
		public System.DateTime SalesDate
		{
			get
			{
				return this._SalesDate;
			}
			set
			{
				if ((this._SalesDate != value))
				{
					this.OnSalesDateChanging(value);
					this.SendPropertyChanging();
					this._SalesDate = value;
					this.SendPropertyChanged("SalesDate");
					this.OnSalesDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SalesNumber
		{
			get
			{
				return this._SalesNumber;
			}
			set
			{
				if ((this._SalesNumber != value))
				{
					this.OnSalesNumberChanging(value);
					this.SendPropertyChanging();
					this._SalesNumber = value;
					this.SendPropertyChanged("SalesNumber");
					this.OnSalesNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ORNumber
		{
			get
			{
				return this._ORNumber;
			}
			set
			{
				if ((this._ORNumber != value))
				{
					this.OnORNumberChanging(value);
					this.SendPropertyChanging();
					this._ORNumber = value;
					this.SendPropertyChanged("ORNumber");
					this.OnORNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,5) NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATSales", DbType="Decimal(18,5) NOT NULL")]
		public decimal VATSales
		{
			get
			{
				return this._VATSales;
			}
			set
			{
				if ((this._VATSales != value))
				{
					this.OnVATSalesChanging(value);
					this.SendPropertyChanging();
					this._VATSales = value;
					this.SendPropertyChanged("VATSales");
					this.OnVATSalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NonVATSales", DbType="Decimal(18,5) NOT NULL")]
		public decimal NonVATSales
		{
			get
			{
				return this._NonVATSales;
			}
			set
			{
				if ((this._NonVATSales != value))
				{
					this.OnNonVATSalesChanging(value);
					this.SendPropertyChanging();
					this._NonVATSales = value;
					this.SendPropertyChanged("NonVATSales");
					this.OnNonVATSalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATAmount", DbType="Decimal(18,5) NOT NULL")]
		public decimal VATAmount
		{
			get
			{
				return this._VATAmount;
			}
			set
			{
				if ((this._VATAmount != value))
				{
					this.OnVATAmountChanging(value);
					this.SendPropertyChanging();
					this._VATAmount = value;
					this.SendPropertyChanged("VATAmount");
					this.OnVATAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Customer
		{
			get
			{
				return this._Customer;
			}
			set
			{
				if ((this._Customer != value))
				{
					this.OnCustomerChanging(value);
					this.SendPropertyChanging();
					this._Customer = value;
					this.SendPropertyChanged("Customer");
					this.OnCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="NVarChar(255)")]
		public string Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this.OnDiscountChanging(value);
					this.SendPropertyChanging();
					this._Discount = value;
					this.SendPropertyChanged("Discount");
					this.OnDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeniorCitizenId", DbType="NVarChar(255)")]
		public string SeniorCitizenId
		{
			get
			{
				return this._SeniorCitizenId;
			}
			set
			{
				if ((this._SeniorCitizenId != value))
				{
					this.OnSeniorCitizenIdChanging(value);
					this.SendPropertyChanging();
					this._SeniorCitizenId = value;
					this.SendPropertyChanged("SeniorCitizenId");
					this.OnSeniorCitizenIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeniorCitizenName", DbType="NVarChar(255)")]
		public string SeniorCitizenName
		{
			get
			{
				return this._SeniorCitizenName;
			}
			set
			{
				if ((this._SeniorCitizenName != value))
				{
					this.OnSeniorCitizenNameChanging(value);
					this.SendPropertyChanging();
					this._SeniorCitizenName = value;
					this.SendPropertyChanged("SeniorCitizenName");
					this.OnSeniorCitizenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeniorCitizenAge", DbType="Int")]
		public System.Nullable<int> SeniorCitizenAge
		{
			get
			{
				return this._SeniorCitizenAge;
			}
			set
			{
				if ((this._SeniorCitizenAge != value))
				{
					this.OnSeniorCitizenAgeChanging(value);
					this.SendPropertyChanging();
					this._SeniorCitizenAge = value;
					this.SendPropertyChanged("SeniorCitizenAge");
					this.OnSeniorCitizenAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terminal", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Terminal
		{
			get
			{
				return this._Terminal;
			}
			set
			{
				if ((this._Terminal != value))
				{
					this.OnTerminalChanging(value);
					this.SendPropertyChanging();
					this._Terminal = value;
					this.SendPropertyChanged("Terminal");
					this.OnTerminalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCancelled", DbType="Bit NOT NULL")]
		public bool IsCancelled
		{
			get
			{
				return this._IsCancelled;
			}
			set
			{
				if ((this._IsCancelled != value))
				{
					this.OnIsCancelledChanging(value);
					this.SendPropertyChanging();
					this._IsCancelled = value;
					this.SendPropertyChanged("IsCancelled");
					this.OnIsCancelledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
